//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VirtualLine2._0.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Queue
    {
        public string Username { get; set; }
        public string Phone { get; set; }
        public int Position { get; set; }
        public int Bar { get; set; }
        public System.DateTime StartTime { get; set; }
        public bool timerStarted { get; set; }
        public Nullable<bool> enteringBar { get; set; }
        public int Quantity { get; set; }
        public int ExtendTime { get; set; }
        public bool NotificationSent { get; set; }
        public Nullable<decimal> PricePoint { get; set; }
        public bool GotFlicNotification { get; set; }
    }
}
