//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VirtualLine2._0.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class QueueTime
    {
        public int VenueId { get; set; }
        public Nullable<System.TimeSpan> SundayOpen { get; set; }
        public Nullable<System.TimeSpan> MondayOpen { get; set; }
        public Nullable<System.TimeSpan> TuesdayOpen { get; set; }
        public Nullable<System.TimeSpan> WednesdayOpen { get; set; }
        public Nullable<System.TimeSpan> ThursdayOpen { get; set; }
        public Nullable<System.TimeSpan> FridayOpen { get; set; }
        public Nullable<System.TimeSpan> SaturdayOpen { get; set; }
        public Nullable<System.TimeSpan> SundayClose { get; set; }
        public Nullable<System.TimeSpan> MondayClose { get; set; }
        public Nullable<System.TimeSpan> TuesdayClose { get; set; }
        public Nullable<System.TimeSpan> WednesdayClose { get; set; }
        public Nullable<System.TimeSpan> ThursdayClose { get; set; }
        public Nullable<System.TimeSpan> FridayClose { get; set; }
        public Nullable<System.TimeSpan> SaturdayClose { get; set; }
    }
}
