//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VirtualLine2._0.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class VenueEntry
    {
        public string VenueName { get; set; }
        public System.DateTime TimeStamp { get; set; }
        public int Id { get; set; }
        public int VenueId { get; set; }
        public Nullable<decimal> PricePoint { get; set; }
    }
}
